### ISSUE TITLE
Improvement request: send mail attachments if "allowattachments" is enable

### ISSUE THREAD

**Issue by ghartwig** [lsuits/block_quickmail#131]
Hi,

many thanks to the contributors of the well working plugin quickmail.

I have an improvement request for next versions of quickmail:

Between Moodle 2.5 and 2.6 there is a difference by sending mail attachments via quickmail. In Moodle 2.5 the attachement were sent als zip-file directly within in the mail, which is sent from moodle to the receivers.
In Moodle 2.6 there is just a link to download mail attachement. The receivers were forced to logon in moodle to download the attachment.

Now my request for moodle 2.6 (and higher):
In website-administration > plugins > message outputs > mail we'll find the option to allow sending attachment (allowattachments). Is it possible to send the mail attachemnt directly in the mail (like in Moodle 2.5) if the Option is enable?

Best regards
Gerald

**Comment by rrusso** [comment]
This is live in the Moodle plugins repo and on dev-30
