### ISSUE TITLE
Mails are send without line breaks

### ISSUE THREAD

**Issue by benidroe** [lsuits/block_quickmail#137]
I have found out that many mails from the quickmail block are sent without line breaks.

When I use the moodle HTML-Editor everything is ok. The Students get a HTML-formatted mail and everything works fine.

However, when I use the plain-text editor, line-breaks are ignored in the mail. The complete message is written in only one line.

Is there any possibility to fix this?

**Comment by elliott2081** [comment]
Hello Kathrin84! I am currently looking into it. I'm not sure what's causing it so I can't give a great timeline for when it will be fixed. I would guess soonish though.

**Comment by elliott2081** [comment]
Hello @Kathrin84 and @benidroe , 
If you go to the latest commit for the 'dev' branch of quickmail this issue should be fixed. It probably won't be available as the main quickmail for awhile, maybe a month or two. 
I'd be interested if you find cases where it doesn't work though because I'm not 100% that all possible permutations are accounted for. 
Also, if you have the simple plain text editor selected with the 'HTML Format' option selected beneath it, it will still do the same behavior as it's expecting the user to supply HTML code, the other options should be plain text with spaces and line breaks though. I mostly used the 'moodle auto-format' option.

**Comment by Kathrin84** [comment]
Since it's almost 3 months since your last comment on this issue, my question is, when the fix will be added to the master branch of the plugin as long as we can only use the master branches?
Thanks in advance!

**Comment by elliott2081** [comment]
Hello @Kathrin84 , I thought that was in the master branch, as of 22 days ago. I will check on it.

**Comment by rrusso** [comment]
I've verified that this change is indeed in the Master branch. @Kathrin84 please review and let me know if this is working for you.

**Comment by rrusso** [comment]
We're working on it.

**Comment by Kathrin84** [comment]
I verified it again and I got the following behavior (all of course in combination with the setting to plain text area editor within the user profile settings)
- HTML: no line breaks
- Plain Text: no line breaks
- Markdown: no line breaks
- Moodle-Auto-Format: line breaks

**Comment by elliott2081** [comment]
HTML and I guess markdown won't have line breaks unless you put the code/markdown in. Does that make sense? Plain text did have line breaks at one point, but it seems to have gotten a bug recently and I'm currently tracking it down. Is there a reason you don't want to use Moodle-auto-format? 
As of right now I'm also getting a bug where if the sender sends an HTML message to a user that has selected to not receive html in his noodle preferences, that message does not work. Is that happening to you?

**Comment by Kathrin84** [comment]
It's not about what I use in Moodle, it's about what our trainers and students want to use as their text editor. And we have users that insist to use plain text. And it would be great if the plugin would work without bugs in the displaying for them, too. :)

I've tested your second case you mentioned. Yes, it's also happening in my system. Mails with HTML to receive only plain text follows up in a text'worm' without any linebreaks and spaces...

**Comment by rrusso** [comment]
This is fixed in the moodle.org plugins repository and on dev-30.
