### ISSUE TITLE
Quickmail for moodle 2.7

### ISSUE THREAD

**Issue by ismaelmartin** [lsuits/block_quickmail#143]
Hi, 

I can't install this current release on my moodle. My moodle version is 2.7, It's compatible with this current release of Quickmail?

Thanks in advance!

**Comment by leblangi** [comment]
Just use the zip file from the github project, its generally more up to date:
https://github.com/lsuits/quickmail/archive/master.zip

**Comment by Kathrin84** [comment]
The version of quickmail in the moodle plugin repository is several months behind your master branch. We would like to use the version of the plugin repository and not that from github. Would you please update the version in the moodle plugin repository?

**Comment by elliott2081** [comment]
@Kathrin84 Should be there soon. Github and the plugin repo are not necessarily going to have the same version. Just because something is on master it doesn't mean that it has been fully tested and deployed yet and usually we update the plugin repo at a major release, but that will be happening quite soon.

**Comment by roxperez** [comment]
I downloaded both versions (master on github and the folder in moodle repository) and in both cases I´m getting this error:

PHP catchable fatal error

Warning: array_filter() expects parameter 2 to be a valid callback, no array or string given in /furanet/sites/eusol.es/web/htdocs/formacion/blocks/quickmail/settings.php on line 25

Warning: array_keys() expects parameter 1 to be array, null given in /furanet/sites/eusol.es/web/htdocs/formacion/blocks/quickmail/settings.php on line 33

Debug info: Object of class stdClass could not be converted to string
Error code: codingerror
Stack trace:
    line 393 of /lib/setuplib.php: coding_exception thrown
    line 3117 of /lib/adminlib.php: call to default_error_handler()
    line 6863 of /lib/adminlib.php: call to admin_setting_configmultiselect->output_html()
    line 6838 of /lib/adminlib.php: call to admin_output_new_settings_by_page()
    line 6838 of /lib/adminlib.php: call to admin_output_new_settings_by_page()
    line 6838 of /lib/adminlib.php: call to admin_output_new_settings_by_page()
    line 30 of /admin/upgradesettings.php: call to admin_output_new_settings_by_page()

**Comment by abias** [comment]
@elliott2081 It's been a while now since you told us that there would be an updated version in the Moodle plugin repo. Could you please tell us what's keeping you from publishing an up-to-date version there? Can we use the version from github's master branch in production on Moodle 2.8?

**Comment by elliott2081** [comment]
Hello Alexander,
I'm currently working in an automated test suite, which will hopefully make it quicker in he long run to verify that future versions are well tested before release, I have hit some bumps in the road, but as far as I can tell the master branch does work in 2.8 and some larger schools seem to have started using it.

**Comment by abias** [comment]
Ok, thanks for the information. We are currently rolling out 2.8 and will report back if anything fails.

**Comment by abias** [comment]
@elliott2081 I wanted to report you back that the version Quickmail from Github master branch runs smoothly in Moodle 2.8 from our point of view.

We would _really_ appreciate it if you could update the Moodle plugin repository with a current version.
