### ISSUE TITLE
Rolenames in configuration dialogue

### ISSUE THREAD

**Issue by abias** [lsuits/block_quickmail#146]
Hi,

on /admin/settings.php?section=blocksettingquickmail, the roles are listed with shortnames, on /blocks/quickmail/config_qm.php?courseid=XYZ, the roles are listed with longnames. I think this should be changed to longnames for both dialogues for better understanding.

Thanks, Alex

**Comment by rrusso** [comment]
In Moodle, you are not required to have a role->name. The DB entry can be an empty string, therefore the above method will return a bunch of nothing for any roles not deliberately named by the Moodle admin.

Instead, I'm committing this to dev-30 and this will be in the plugins repo in the next week. We've done multiple updates today and I don't want to piss people off with too many updates.

$only_names = function ($role) { return $role->name ? trim(format_string($role->name)) : $role->shortname; };

This will ensure that if the role->name doesn't exist, we still get the role->shortname. I've tested this with a mixed bunch of existing and non-existing role names and it seems GTG.

Check the latest dev-30 for the change.
