### ISSUE TITLE
Make "Additional Emails" feature optional

### ISSUE THREAD

**Issue by abias** [lsuits/block_quickmail#147]
Hi,

in Quickmail, there is the new feature "Additional Emails". As an admin, I would like to disable this feature with a setting because we don't want users to send emails to others than our Moodle users.

Thanks, 
Alex

**Comment by rlorenzo** [comment]
We just discovered this new setting and were shocked to see that the default is set to No. That changed the current behavior that is expected for the user. Shouldn't the default be to Yes to keep current existing behavior and anyone who wanted it changed would set it to No?

**Comment by elliott2081** [comment]
I think it's set to yes, as a way of encouraging people to use it and noticing the new feature. I think there's probably a good argument either way.
