### ISSUE TITLE
View History status giving incorrect readout

### ISSUE THREAD

**Issue by jasperboyd** [lsuits/block_quickmail#155]
Forgive me if this was not the way the feature was speced but I was testing whether or not the use of a bad email would give a readout in the view history and it returned "all messages sent successfully", even though the email definitely doesn't exist. If this was not the way the feature is supposed to work is there a way to retrieve an "email doesn't exist reply" from an exchange server?

**Comment by rrusso** [comment]
Retrieving server 550 errors from remote email servers is beyond the scope of quick mail.
