### ISSUE TITLE
Sender Email

### ISSUE THREAD

**Issue by ssllqq** [lsuits/block_quickmail#157]
Hi,

Need function send emails using sender email address or replay-to using sender email address.

Thanks

**Comment by benoitlathiere** [comment]
Hi!

It's already available. You just need to check two conditions (according to the system function _email_to_user()_ ):

- specify some allowed email domains (system parameter: _allowedemaildomains_),
- the sender needs to accept its email address visibility in its profile (visibily in a course or for everyone).

Thereby, the original sender email address do will appears in the recipient's mail client, in place of the 'noreplay' generic address.

This works fine in Moodle 3.2.

**Comment by rrusso** [comment]
This is working already in dev-30 and the version in the Moodle Plugin Repo.
