### ISSUE TITLE
email.php is not processing the plugin file URLs properly for message text

### ISSUE THREAD

**Issue by agrowe** [lsuits/block_quickmail#173]
In `email.php`, when it tries to send an email, it is processing the plugin file urls for `$data->message` but then that variable is not used anywhere else. It is sending the email text with `$data->messageWithSigAndAttach`. This means that emails which embed an image are sent with the source still having `@@pluginfile@@/` in it.

To fix this in the dev branch, comment out line 275
`$data->message = file_rewrite_pluginfile_urls($data->message, 'pluginfile.php', $context->id, 'block_quickmail', $table, $data->id, $editor_options);`

and then paste that exact same line in between line 263 and 264. That is just before `$data->message` is used and then becomes `$data->messageWithSigAndAttach`

Thanks
Alex

**Comment by rrusso** [comment]
This is quite a bit more complicated than is stated. Even with the change, the embedded image is not base64 encoded and sent via quick mail. Instead a link is sent which cannot be loaded by any external email client like google or MS as they cannot log in to retrieve the image.

This will only work in local email systems that display messages in an HTML window that shares a session with the open OS browser (IE used to do this in outlook, I'm unsure if they still do).

I'm going to look into base64 encoding before I make any change.

**Comment by agrowe** [comment]
We haven't had any issues with this code change over the last few years and have had to make similar changes in previous versions.

In the `lib.php` file for `block_quickmail_pluginfile`, if you have the setting `$CFG->block_quickmail_downloads` set then you don't need to have logged in.

**Comment by rrusso** [comment]
This is absolutely correct, but it breaks for people like us who require logins. 

I'll come up with a solution for everyone. It shouldn't be too insane.

**Comment by rrusso** [comment]
I've given up on the idea of embedding them via base64 encoding and came up with a compromise that allow non-authenticated downloading of images within the email body, but still requires login (if selected) for attachments added via the attachment UI.

This fix will go into the Moodle plugins repo tomorrow along with other ancillary fixes.

This fix is on dev-30.
