### ISSUE TITLE
error message during phpunittest: Failed opening required ... ferpa.QM.BehatGenerator.php

### ISSUE THREAD

**Issue by moodlebeuth** [lsuits/block_quickmail#176]
Hello,

I am using moodle 2.8.5 with postgresql and the quickmail plugin with the master branch (version = 2015122912) and I tried to make a phpunit test. But I've got the following error message:
http://pastebin.com/cQvTw55D

Please, could you help me? Is there a missing file or just a wrong file name in the BehatGenerator_test.php?

Thanks & Greetings,
Michael

**Comment by elliott2081** [comment]
yes, when we were making that file someone named it something that behat
doesn't like(goes against convention). I can't specifically troubleshoot
your phpunit errors, but downloading the latest version will solve the file
name problem.
