### ISSUE TITLE
Selecting groups and role filters not always working in Firefox and IE 11

### ISSUE THREAD

**Issue by mr-cfollin** [lsuits/block_quickmail#186]
In Firefox 39 and Internet Explorer 11, selecting users using groups and role filters does not always work correctly. Make multiple changes to the filters and the Potential Recipients will stop changing or no longer select any.

Reproduce by playing with Role Filter and Potential Sections, noting the Potential Recipients.

In Firefox for Windows:
- Create two groups: group 1 and group 2
- Add some users to each
- In Quickmail, select Group 1 from Potential Sections and note selections in Potential Recipients (correct)
- Select Group 2 from Potential Sections and note selections in Potential Recipients (correct)
- Select Group 1 again
EXPECTED: Group 1 users highlighted
ACTUAL: No user is highlighted at all in Potential Recipients

This happens in all themes.  Does not happen in Chrome; only Firefox and IE 11 (that we've found).

**Comment by Syxton** [comment]
This issue still exists

**Comment by robinleung** [comment]
This issue still exists with latest version of Firefox.

**Comment by Syxton** [comment]
This has been merged on the MOODLE_STABLE_30 branch

**Comment by robinleung** [comment]
Is this different from the latest version 1.5.5 in the Moodle plugins directory?

**Comment by Syxton** [comment]
That last release shown on github is a 1.5 release candidate, so it is hard to really tell, but the MOODLE_STABLE_30 branch is 5 commits ahead of master, and master hasn't been touched since Aug of last year.

**Comment by robinleung** [comment]
Thanks! Hence, MOODLE_STABLE_30 is recommended for Moodle 3.0+?

**Comment by Syxton** [comment]
Looking at the changes on the MOODLE_STABLE_30 branch, only the firefox jquery fix is included past version 1.5.5.  So it will work.  We are currently running 2.8 with 1.5.5 and the firefox fix

**Comment by robinleung** [comment]
Thanks for the help!

**Comment by robinleung** [comment]
Just installed MOODLE_STABLE_30 branch & issue persists with Firefox (latest versions) on Mac & PC, as well as, Internet Explorer. Works fine with Chrome.
Currently on Moodle 3.0.3 (Build: 20160314)

**Comment by elliott2081** [comment]
We are currently in the process of upgrading all our plugins and quickmail is being worked on again currently. As of right now, MOODLE_STABLE_30 is not what I would actually consider stable and should probably change the branchs' name

**Comment by Syxton** [comment]
Also, since the MOODLE_STABLE_30 is still running 1.5.5, I'm assuming Moodle didn't run through an upgrade process.  In this case, the fixes are done in javascript so you must purge caches for the new javascript to get loaded.  Since the upgrade didn't bump version numbers, this wouldn't be done automatically.

**Comment by robinleung** [comment]
Thanks all! All is working fine for now after purging cache on all browsers.
