### ISSUE TITLE
Atto autosave overwrites history

### ISSUE THREAD

**Issue by amandadoughty** [lsuits/block_quickmail#187]
1. Go to Quickmail->View History
2. Open an email.
3. Wait for the time that the atto editor is set to autosave (default 1 min) 'Draft saved' will flash.
4. Go to Quickmail->View History
5. Open a different email.
6. The content displayed is that of the first email opened. It is the same for every email. 
7. Turn JS off and the correct content is displayed.

A record is created in editor_atto_autosave that is used to overwrite the content of every email text editor box.

**Comment by elliott2081** [comment]
Thanks! Looking into it.

**Comment by amandadoughty** [comment]
I'm off on hols for a week so I've added a quick diff patch to the issue on Moodle Tracker: https://tracker.moodle.org/browse/CONTRIB-5864

It just appends the log id the editor id (id_message_editor), so that should stop other logs being overwritten. I have not had time to extensively test but I'm hoping you would know if that could cause any kind of regression? I can test more thoroughly when I get back.

**Comment by rrusso** [comment]
Fixed in latest dev-30
