### ISSUE TITLE
Use "Notification email override"

### ISSUE THREAD

**Issue by rlorenzo** [lsuits/block_quickmail#188]
Moodle has a setting called "Notification email override" (messagingallowemailoverride) that allows users to have email message notifications sent to an email address other than the email address in their profile.

Quickmail doesn't take that email address into account when sending out emails.

**Comment by rrusso** [comment]
Rex, sorry if the previous maintainer hadn't been responsive, but how do you guys handle spf problems that arise from sending from an email address that isn't part of your domain? 
Or do you only suggest using this in the to: field?

**Comment by rrusso** [comment]
Never-mind. This is for recipient notifications. This is in the latest dev-30.
