### ISSUE TITLE
Quickmail and Mac/iPad

### ISSUE THREAD

**Issue by francescodamico** [lsuits/block_quickmail#194]
Here is my issue.

Unfortunately I think there is a bug in the Quickmail plugin.
I'm using Moodle 2.7 and I have installed the last version of the Quickmail plugin.
This is the issue:
I have a course set with 4 separate groups. If I'm using my Mac or my iPad, or if I'm surfing the net on my PC using a private/incognito window, I can't send any message to the members of the group I am in. This is the error message that appears: 'There are no users you are capable of emailing'.

No problem if I am using my PC.

Any hints?

Thank you,

Francesco

**Comment by rrusso** [comment]
This bug has been fixed.
