### ISSUE TITLE
Quickmail will not install on a Moodle 3.0 site due to missing $plugin->component in version.php

### ISSUE THREAD

**Issue by ttsilva90** [lsuits/block_quickmail#196]
Attempting to install the plugin on a Moodle 3.0 site results in the following error:

Plugin "block_quickmail" is defective or outdated, can not continue, sorry.
Debug info: Missing $plugin->component declaration in version.php.
Error code: detectedbrokenplugin

**Comment by rrusso** [comment]
Use the MOODLE_STABLE_30 branch.

**Comment by clintr55** [comment]
I have a similar problem, where can I find the download?

**Comment by DrFlo** [comment]
same here, trying the moodle stable 30 branch

Moodle 3.0.2+ (Build: 20160225), Ubuntu 14.04 LTS

Plugin mod_quickmail does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 758 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 668 of /admin/index.php: call to core_plugin_manager->all_plugins_ok()
Invalid get_string() identifier: 'modulename' or component 'mod_quickmail'. Perhaps you are missing $string['modulename'] = ''; in mod/quickmail/lang/en/quickmail.php?
line 349 of /lib/classes/string_manager_standard.php: call to debugging()
line 6676 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
line 64 of /lib/classes/plugininfo/mod.php: call to get_string()
line 142 of /lib/classes/plugininfo/base.php: call to core\plugininfo\mod->init_display_name()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 758 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 668 of /admin/index.php: call to core_plugin_manager->all_plugins_ok()
Skip to main content


Plugin "block_quickmail" is installed in incorrect location "$CFG->dirroot/mod/quickmail", expected location is "$CFG->dirroot/blocks/quickmail"

More information about this error

Debug info: 
Error code: detectedmisplacedplugin
Stack trace:
line 631 of /lib/upgradelib.php: plugin_misplaced_exception thrown
line 427 of /lib/upgradelib.php: call to upgrade_plugins_modules()
line 1641 of /lib/upgradelib.php: call to upgrade_plugins()
line 677 of /admin/index.php: call to upgrade_noncore()

**Comment by elliott2081** [comment]
Are you trying to install it in the /mod/ folder? It needs to go in the /blocks/ folder.

**Comment by DrFlo** [comment]
Yes sorry, figured that earlier as well. Works like a charm. Blame on me :(

Thank you

**Comment by roperto** [comment]
Hi all. I am having this problem with Moodle 31. Is there any specific reason not to support 31?
```
Plugin block_quickmail does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 96 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
line 758 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
line 674 of /admin/index.php: call to core_plugin_manager->all_plugins_ok()
```

**Comment by roperto** [comment]
I created the pull request with the missing line:

https://github.com/lsuits/block_quickmail/pull/216

CI is failing (Travis) due to missing configuration. If the author is interested I can try to help setting up Travis.

Cheers,
Daniel
