### ISSUE TITLE
HTML formatting stripped from manually entered email addresses

### ISSUE THREAD

**Issue by RyanBernstein** [lsuits/block_quickmail#197]
Hello, 

We've noticed that in Moodle 2.9, HTML formatting is stripped from Quickmail email messages to recipients whose email address was manually entered into the 'Additional email addresses' field. Recipients who were selected from the 'Potential recipients' (enrolled users), received emails with HTML formatting intact.
![email1](https://cloud.githubusercontent.com/assets/15349407/10770551/45599384-7cc2-11e5-830d-6d5713dab6b0.jpg)
 Thanks!

**Comment by rrusso** [comment]
I'm not able to replicate.

![screen shot 2015-12-02 at 1 57 58 pm](https://cloud.githubusercontent.com/assets/642570/11542405/cf85e002-98fc-11e5-845d-8b53bcaeb1d8.png)

![img_2401](https://cloud.githubusercontent.com/assets/642570/11542419/d970620e-98fc-11e5-9639-681ea5e86ebf.PNG)

**Comment by rrusso** [comment]
I'm not able to replicate.

![screen shot 2015-12-02 at 1 57 58 pm](https://cloud.githubusercontent.com/assets/642570/11542465/08a2e402-98fd-11e5-861b-b937685cd46e.png)
![img_2401](https://cloud.githubusercontent.com/assets/642570/11542471/10f0df9c-98fd-11e5-87ec-8dbaf5cdd6a9.PNG)
