### ISSUE TITLE
Compose an email when the course has no users in it throws a Moodle error

### ISSUE THREAD

**Issue by markchaneyuk** [lsuits/block_quickmail#204]
If the course contains no enrolled users (direct enrolled users as opposed to category enrolled users) and you try and compose an email, the plugin throws a debug and stack trace with the message "There are no users in your group capable of being emailed.". 

Ideally this should not throw a Moodle error. 

This is on Moodle 3.0.2 with plugin version 2015122912

**Comment by elliott2081** [comment]
Thanks. I'll change it to just post the information as text and not throw a debug error.

**Comment by rrusso** [comment]
I am assigning @chadmazilly to this one.

**Comment by chadmazilly** [comment]
This is now fixed. I just simply removed the check to see if there are any available users to email. It should now display as usual, but with no available users to email. #[0400731](https://github.com/lsuits/block_quickmail/commit/0400731ece6fe6222b7be21469d2cc34b1feffbc)
