### ISSUE TITLE
Hardcoded language strings in quickmail block

### ISSUE THREAD

**Issue by lucaboesch** [lsuits/block_quickmail#206]
Hi

At least at two points there are hard coded language strings in quickmail. They concern negations meaning "No" as in "No signature" or "New" as in "New signature". This doesn't work out if "signature" is taken out of a localized lang file. It would be better to localize the "Signature", the "No signature" and "New signature" separately and respectively as a whole.

signature.php, Line 138: `$first = array(0 => 'New '.quickmail::_s('sig'));`
email_form.php, Line 215: `$options = $this->_customdata['sigs'] + array(-1 => 'No '. quickmail::_s('sig'));`

were the part's I've found such occuring behaviour. There could be more like this.

Best regards

**Comment by elliott2081** [comment]
thanks. Merged the pull request that addressed this issue.

**Comment by lucaboesch** [comment]
Wait, what pull request?
I'd urge you to reopen, still seems pretty hardcoded to me.
