### ISSUE TITLE
Can't backup course with 2 Quickmail block instances

### ISSUE THREAD

**Issue by SWiT** [lsuits/block_quickmail#208]
If a course has 2 Quickmail blocks added to it. (via import/Backup/Restore) The Backup menu will not load. You will get a "setting_already_added" error.

**Comment by rrusso** [comment]
Delete the instance.

We will make changes so this does not happen in the future.

On Aug 16, 2016, at 10:49 AM, Matthew G. Switlik <notifications@github.com<mailto:notifications@github.com>> wrote:


If a course has 2 Quickmail blocks added to it. (via import/Backup/Restore) The Backup menu will not load. You will get a "setting_already_added" error.

**Comment by elliott2081** [comment]
closing
