### ISSUE TITLE
Selecting recipients by Potental Sections

### ISSUE THREAD

**Issue by davidlanier** [lsuits/block_quickmail#209]
When selecting recipients by using the Potential Sections select list, after several iterations of selecting and adding, then removing some users the Javascript appears to stop working and clicking on a "section" in the Potential Sections select list fails to subsequently select recipients in the Potential Recipients select list. 

Reloading the page drops all of the previously selected recipients out of the Selected Recipients list so that is not a very good work around in lieu of a permanent fix.

**Comment by rrusso** [comment]
We've not seen this behavior. What browser / OS / version are you using and how many iterations are required to reproduce?

**Comment by davidlanier** [comment]
We tested on Chrome and Firefox on Windows 10 and Debian Linux and found that it fails after just three iterations. We also tested in Chrome on Mac and it failed there too, but it did work in Safari although after the 3rd iteration the list in the Potential Recipients stopped being highlighted in Safari, but we were still able to add them.

We recommend change all instances of `.attr("selected")` to `.prop('selected')` to correct the problem.

Thanks

**Comment by markchaneyuk** [comment]
Dear all, as I have commented in the other issue. We too experience this issue. Chrome and Firefox. Moodle 3.0.3 plugin version 2015122912.

**Comment by jamatrucola** [comment]
This sounds like the same issue I reported in #200 in December, 2015.

**Comment by elliott2081** [comment]
merged. thanks.
