### ISSUE TITLE
Problem when selecting/adding recipients using Internet Explorer

### ISSUE THREAD

**Issue by cdipe** [lsuits/block_quickmail#215]
Selecting/adding recipients doesn't work with Internet Explorer 11. 
Works with Edge, Firefox, Chrome and Safari.

Using QuickMail v1.5.5 2015122912 and Moodle 3.0.5

**Comment by rrusso** [comment]
I'm not able to replicate this using Internet Explorer 11.1066.14393.0 (11.0.41) in Windows 10.
