### ISSUE TITLE
Error when sending an email: username not defined.

### ISSUE THREAD

**Issue by roperto** [lsuits/block_quickmail#218]
When sending an e-mail with Moodle 31 we get that username is not defined.

**Comment by Kathrin84** [comment]
With Moodle 3.2 there's the same error:

> Notice: Undefined property: stdClass::$username in /var/www/html/moodle_dev2/lib/moodlelib.php on line 5939

**Comment by rrusso** [comment]
Thank you for this. Our next update will deal with this notice.

**Comment by chadmazilly** [comment]
This is now fixed. #[24d5651](https://github.com/lsuits/block_quickmail/commit/24d5651c78e00e0a4bed1d694c69aed2aaf87c61)
