### ISSUE TITLE
version 1.5.5 (Moodle 3.1) not available

### ISSUE THREAD

**Issue by euneuber** [lsuits/block_quickmail#219]
I'd like to download Moodle plugins from github, but this repository seams not up to date...

Please edit https://moodle.org/plugins/pluginversions.php?plugin=block_quickmail or update this repository! Thank you.

**Comment by rrusso** [comment]
The main repo (dev-30) is now compatible with 3.1. We are handing off responsibilities for keeping QM updated to @chadmazilly. He will be far more diligent in his duties.
