### ISSUE TITLE
Server 500 error

### ISSUE THREAD

**Issue by jmj5g** [lsuits/block_quickmail#221]
Greetings,

I have a client with Quickmail installed on Moodle 3.0.x and it has been working fine for a couple of years. Recently Quickmail started returning Server 500 errors. We had not changed anything about the Moodle installation. My hunch is that the hosting company upgraded something related to Apache or PHP, and it is causing it to break. Can you provide any hints as to what might cause this to happen?
thanks!
John

**Comment by rrusso** [comment]
Can you turn on debugging and email debugging and let us know what you see?

**Comment by jmj5g** [comment]
I found the problem. It was a permissions setting on the quickmail php files. The hosting company must have made a global permissions change, for I didn't touch it. But setting the permissions correctly resolved the issue. Many thanks for your response though.
