### ISSUE TITLE
 Selection of potential users stop working after the first group changes.

### ISSUE THREAD

**Issue by llisboa** [lsuits/block_quickmail#222]
Using Moodle version 3.0.8, Quickmail 2015122912, changing selected groups only works the first time.
In the file js/selection.js file, the line  -> return $(option).attr('selected', selected); <- simply stop working after the first selections.
I solved the problem by replacing it with -> return $ (option) .prop ('selected', true); <-

**Comment by rrusso** [comment]
What browser are you working in where the problem manifests? 

I've not been able to replicate this locally in Safari, Chrome, Edge, and Firefox.

**Comment by rrusso** [comment]
This has been tested across the board including IE Edge. I am unable to test in older versions of Internet Explorer.
