### ISSUE TITLE
Mail not being sent

### ISSUE THREAD

**Issue by jmj5g** [lsuits/block_quickmail#224]
Greetings,

My client is running Moodle 3.0.6+ on LAMP, and has been using Quickmail for quite a while with no problem. Now when trying to send a message the client reports getting this error:

Warning: Error while sending QUERY packet. PID=47843 in /home/tsogya5/public_html/tsogyalonlinecourses.com/lib/dml/mysqli_native_moodle_database.php on line 1391

When I test, logged in as a sys admin or a teacher, I do not get that error, but I do get a more generic error of "Cannot send mail to <user name>." I have turned on full developer debugging, but no errors are displayed.

Suggestions?

Thanks!
John Jackson

**Comment by rrusso** [comment]
Turn on debug email sending. It's most likely an issue with SMTP.

**Comment by jmj5g** [comment]
Thanks for your quick reply. I turned on the debug email sending and ran another test. No error messages were displayed on screen. Would the error be put into a log somewhere?

**Comment by rrusso** [comment]
I believe debugging (developer) to screen must be turned on. When you send an email, you'll get a metric ton of output related to the entire SMTP process. If that doesn't happen, and you get a DB error, you have a DB problem that needs to be investigated asap.

**Comment by jmj5g** [comment]
I have developer debugging turned on as well as debug mail sending, and performance info. Still no errors displayed on screen. No DB error either. Just "Cannot send mail to XXXXXX ."

**Comment by rrusso** [comment]
Are you using local SMTP? Or an external SMTP server? If it's local, it sounds like a server problem. If it's remote, you should have lots of messages related to connecting to the service.

**Comment by jmj5g** [comment]
Found the problem. Misconfiguration of the SMTP server settings. Many thanks for putting me on the right track.
