### ISSUE TITLE
Compose New Mail Role Filter

### ISSUE THREAD

**Issue by jamesmcq** [lsuits/block_quickmail#233]
Trying to use the role filter on the compose new mail page and I'm not seeing any effects when changing the select box to "Teacher", "Student", and back to "No Filter". Should the users with the selected role be selected when changing this filter?

**Comment by chadmazilly** [comment]
Hey James, just took a look at this and noticed that it does have an effect when the "Potential Sections" selection is selected as "All Users". If that is the case, it seems to perform properly.

**Comment by cyndibishop** [comment]
Hi Chad - From our client, so can you please let me know your thoughts?  "We don't have an "All users" option -- we only get "All Sections" and "Not in a section." And, it looks as if selecting "Not in a section" causes the correct behavior (though I'm pretty sure we tried that already....)

So, what is a "Section" in this context? Is that the same as a group? (The word "section" seems to mostly equate to a "topic" in a course page.) I'm not finding any good documentation for this block, can you point me to some? I'm trying to think of a way to explain this to professors in our how-to guides....."

**Comment by chadmazilly** [comment]
Hey Cyndi,

First, to answer your question about "sections" - yes, they are the same as groups. Here at LSU we have a level of student grouping below the "course level" that we call "sections". So throughout our Moodle customizations you may see that terminology. I just checked and you should be able to modify the "all_sections" lang string to suit your client's own terminology.

Second, you should you have an "All Users" option available by default. This is not the case for you?

Chad

**Comment by Kathrin84** [comment]
Hi everyone,

> Second, you should you have an "All Users" option available by default. This is not the case for you?

I've added a related comment in https://github.com/lsuits/block_quickmail/issues/153:
> I've encountered that "All users" are not displayed if there are no groups existing in the course and and still "All Groups" is highlighted by default. 
I've written a patch for this. This patch displays "All users" always and "All Groups" and the related groups only if there are existing ones within the course.
Additionally, "All users" are highlighted by default.

https://github.com/lsuits/block_quickmail/pull/235

Best, Kathrin

**Comment by cyndibishop** [comment]
Thank you everyone for the assistance. I've reached out to the client and
will be back in touch if anything else is needed.

Sincerely,
Cyndi Bishop



Cyndi Bishop | Premier Case Manager | Remote-Learner US
1550 Larimer Street, Suite 785 | Denver, CO 80202
cyndi.bishop@remote-learner.net | 877-299-1293 Ext. 319
www.remote-learner.net
