### ISSUE TITLE
Codingerror: core_renderer->header()

### ISSUE THREAD

**Issue by relecand** [lsuits/block_quickmail#236]
How to reproduce:

- Moodle 3.1.8
- Quickmail 1.7.1 (from moodle.org)
- Create a course with **just one user**
- add quickmail block
- click "Compose New Email"

The error disappears when more than one user are enrolled into the course.

```
Invalid state passed to moodle_page::set_state. We are in state 3 and state 1 was requested.
Debug info:
Error code: codingerror
Stack trace:

    line 911 of /lib/pagelib.php: coding_exception thrown
    line 953 of /lib/outputrenderers.php: call to moodle_page->set_state()
    line 388 of /blocks/quickmail/email.php: call to core_renderer->header()

```

**Comment by chadmazilly** [comment]
Hey there,

I was able to reproduce the error using the steps provided. I was able to fix the actual bug you are receiving in regards to `codingerror` and put up a new version 1.7.2 which should be available through the Moodle plugin page. Thanks.
