### ISSUE TITLE
No Sent Date - Release v1.7.3 

### ISSUE THREAD

**Issue by goose2000** [lsuits/block_quickmail#238]
Hi, seen this continues to get passed over. I have to fix it everytime I run a plugins update, so going to try to get this fixed. Easy fix, I'll try to do a commit.

![screenshot-ssw unc edu-2017-11-07-10-36-03-927](https://user-images.githubusercontent.com/2395298/32502213-20c47d0c-c3a8-11e7-9301-04bbc25e28b6.png)

**Comment by chadmazilly** [comment]
Hmm that is strange, what is your fix? I can put up a patch real quick.

**Comment by goose2000** [comment]
The format just needs a fix :

static function format_time($time) {
    --      return userdate($time, '%A, %d %B %Y, %I:%M %P');
    ++    return userdate($time, '%d-%m-%Y, %I:%M %p');
   // this will display mm-dd-yyyy, 9:59 AM
    }

**Comment by chadmazilly** [comment]
Well thanks, but I certainly cannot take credit for it. It's been around long before my time with Moodle and LSU. I surely stand on the shoulders of giants :) However, stay tuned for v2.0 which is a complete rewrite! It's going to be awesome.

**Comment by chadmazilly** [comment]
Ok new version (v1.7.4) is up. I did flip the month and day around to display as: mm-dd-yyyy as I think more people are used to this format. I'm sure there is some place in moodle where you can customize this for your personal preference and I'll research that for new releases.

Also, when I did a fresh install of v1.7.3 just not the date seemed to display just fine. I'm wondering if this is a PHP change issue.

If you don't mind, let me know how this update works out for you and I'll close this issue. Thanks again.
