### ISSUE TITLE
Students can send emails through quickmail even with the course configuration set to No

### ISSUE THREAD

**Issue by markt71** [lsuits/block_quickmail#244]
My institution is running both:  
Moodle 3.1.5 with the Quickmail plugin v1.7.1
Moodle 3.3.4 with the Quickmail plugin v1.7.5 
(This issue is occurring on both installs.)

When the block is added to a course page and the quckmail configuration is set as shown below students can still send emails to all members of the course. Could anyone give me some guidance on a resolution. Thank you.

Allow students to use Quickmail: No
Roles to filter by: instructor, TA, student
Prepend Course name: Short name
Receive a copy: No

**Comment by chadmazilly** [comment]
Hey Mark, I've not run across this myself and tests seem to check out fine. One thing to consider: have you changed any quickmail related roles? For example, there is a "cansend" permission that gets checked. If you have the students NOT able to send messages like you stated above, the only way students would be able to send messages is by having that role.
