### ISSUE TITLE
Send messages using progress bar or via background task

### ISSUE THREAD

**Issue by brian-winstead** [lsuits/block_quickmail#246]
When a teacher sends a Quickmail message, the page waits for a response from the server indicating that all outbound emails have been sent.  If the message is being sent to all users in a larger course, such as 300 students, this may take a few minutes to complete.  If the Moodle environment has a load balancer with an idle timeout, this process might take longer than the defined time limit.  If a response is not received after this point the user receives a blank white page or an HTTP 504 error.  When this occurs the outbound emails are still processed and sent successfully, but the end user is likely to interpret the HTTP 504 error as indicating that there was a failure with message delivery.

A better handling of this scenario.  
    1. Message delivery should be moved to a background task. OR
    2. There should be a progress bar that provides feedback on the status of the operation and keeps the connection from idling out, allowing the user to wait until all messages are processed.

**Comment by chadmazilly** [comment]
Hey @brian-winstead, I totally agree. And I'm happy to give you some good news! We're about to release a v2 of Quickmail that does exactly this. Essentially what happens is this... If all of the valid components of a message (recipients, subject, message, etc) are given, then a message record will be created as a db record. We then have a master scheduled task looking to send these messages according to preference (either ASAP, or at a future date/time). When that time comes, the message will be sent, and its individual "children" messages (that message to a specific user) will be fired as adhoc tasks.

So, in the end, the user will compose a message, click send now, and get a success response. The message will then be sent as a background job. The user can still request a send receipt to know it was done, and also view their sent message history.

You can check out this development in our `dev-34` branch. All of this functionality is done, we're just working on a few more details before going beta. It should be relatively stable at the moment if you'd like to pull it in and test it out, but I wouldn't recommend it on a production instance of course as the data structure has completely changed.

These changes will not be applied to the current version of Quickmail as it would require a lot of rewriting that has already been done in the new branch, so I'm going to close the issue.
