### ISSUE TITLE
All emails noreply

### ISSUE THREAD

**Issue by Syxton** [lsuits/block_quickmail#252]
@chadmazilly Not sure if this is the expected behavior or not.  I was informed after our latest update that all email sent out are given noreply email addresses instead of the teacher's email address as the from address.  I would think that this would be tied to the profile option for email display or something like that.  However, it doesn't change anything.

**Comment by Rulontomur** [comment]
We had to note a whitelist with email domains in Moodle 3.5 under 
_Site administration > Server > Email > Outgoing mail configuration: No-reply and domain_ (_allowedemaildomains_). 
After that it worked. I don't know if this had to be necessary in older versions, too. Perhaps helpful.

(Here's a handy list with free email provider domains: [https://gist.github.com/tbrianjones/5992856](https://gist.github.com/tbrianjones/5992856). But for security/performance reasons I guess a shorter list is better.)

**Comment by Syxton** [comment]
@Rulontomur Thanks!  This did fix our issue.  It needs to be better documented indeed.

**Comment by tbahula** [comment]
This fixed our problem too. Didn't see anything in the documentation about this setting.
