### ISSUE TITLE
Server 500 error

### ISSUE THREAD

**Issue by jmj5g** [lsuits/block_quickmail#254]
Greetings,
I just upgraded a client's Moodle installation to 3.4.5, and upgraded QuickMail to 1.7.6 at the same time. No errors during the upgrade. PHP version 7.1.2, MariaDB 10.2.12

The Quickmail block displays properly in a course. However whenever I click on any link in the block, such as "Compose New Email" or "Edit Signatures" I get the vague server error 500. I have turned on javascript debugging, but an getting nothing in the PHP error log or the Apache log. 

What do you suggest?

**Comment by jmj5g** [comment]
I have not resolved this problem.

I have not changed the db tables at all.

For this site Moodle is installed in the root directory. As a result the Moodle path is not www.domain.com/moodle  but instead it is just www.domain.com

Any assistance you can provide is appreciated.

John Jackson

**Comment by chadmazilly** [comment]
Ok, thanks. Are you using Apache? Are you getting 500 errors anywhere else outside of QM?

**Comment by jmj5g** [comment]
Yes, Apache. A standard LAMP installation at inMotion Hosting. 

No other 500 errors.

John

**Comment by rrusso** [comment]
Check your Apache logs and see what they say.

It might be a permissions issue.
