### ISSUE TITLE
Moodle 3.5 supported version ?

### ISSUE THREAD

**Issue by germanvaleroelizondo** [lsuits/block_quickmail#258]
Hi,

This very useful plugin is installed in at least 652 Moodle 3.5 servers according to the stats tab at https://moodle.org/plugins/stats.php?plugin=block_quickmail.

Will you be marking 3.5 as a supported Moodle version anytime soon ?

Or will you wait until you have support for the new Moodle privacy API (https://github.com/lsuits/block_quickmail/issues/248 ) ? 

Thanks in advance.

**Comment by chadmazilly** [comment]
I've been running Quickmail 1.7.6 on Moodle 3.5 for a while now with no problems, though I haven't gone through each feature. I'll test that out today and tag appropriately.

As for the Privacy API, is that required for being tagged as 3.5 compatible now? If that is the case, maybe someone could send in a PR to make that happen. We're just about to release a major upgrade to Quickmail to the plugins directory which will have support for this.

**Comment by germanvaleroelizondo** [comment]
As far as I know, supporting the Moodle privacy API is not yet required for marking a 3.5 compatible plugin, but it is very desirable for Moodle sites with European users.

But I am only a Moodle translator.

Thanks for maintaining this useful plugin and tagging it as 3.5 compatible soon.

**Comment by chadmazilly** [comment]
Successfully tested on 3.5, all works fine. Now tagged as 3.5 compatible in Moodle plugins directory.
