### ISSUE TITLE
Error on "block_quickmail_log" preventing course backup

### ISSUE THREAD

**Issue by logan-reynolds** [lsuits/block_quickmail#263]
When attempting backup of a course containing an instance of block_quickmail version 2018100200 release v2.1.0 I'm getting the following error:

```
Table "block_quickmail_log" does not exist

More information about this error
Debug info:
Error code: ddltablenotexist
Stack trace:

    line 665 of /lib/dml/moodle_database.php: dml_exception thrown
    line 1350 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
    line 10 of /blocks/quickmail/backup/moodle2/backup_quickmail_stepslib.php: call to moodle_database->get_records()
    line 88 of /backup/util/plan/backup_structure_step.class.php: call to backup_quickmail_block_structure_step->define_structure()
    line 181 of /backup/util/plan/base_task.class.php: call to backup_structure_step->execute()
    line 178 of /backup/util/plan/base_plan.class.php: call to base_task->execute()
    line 119 of /backup/util/plan/backup_plan.class.php: call to base_plan->execute()
    line 322 of /backup/controller/backup_controller.class.php: call to backup_plan->execute()
    line 136 of /backup/util/ui/backup_ui.class.php: call to backup_controller->execute_plan()
    line 146 of /backup/backup.php: call to backup_ui->execute()
```

This is a serious error because it prevents backup/restore of courses containing the block.

**Comment by chadmazilly** [comment]
Got it, thanks. We've not yet implemented the backup/restore methods on this new version yet. Will work on that to at least get it out of the danger zone.

**Comment by vcs-edtech** [comment]
Hi Chad, have you been able to implement this yet?

**Comment by logan-reynolds** [comment]
Hello,

Just checking back to see if there's an estimate on when backup/restore functionality related to the block_quickmail_log table will be fixed.

**Comment by rrusso** [comment]
Chad is no longer with us and I have it backing up. I'm trying to get it to restore with the sent messages in the new course right now. Once I'm done, I'll push the changes to master and increment the version.

**Comment by rrusso** [comment]
Backup and Restore are now functional in the latest master and an upgrade will be triggered on install.

**Comment by rrusso** [comment]
Let me know if this is acceptable.

**Comment by vcs-edtech** [comment]
Awesome, thank you Robert… our Moodle host remote-learner is vetting it now!

Jeremy Cunningham, M.Ed
Education Technology Coordinator
VCS.net<http://vcs.net/> | @vcschools<http://twitter.com/vcschools> | @vcs_edtech<https://twitter.com/vcs_edtech>
408.513.2594
[VCS_logo_1C]
