### ISSUE TITLE
New references to fields that are missing from the definition

### ISSUE THREAD

**Issue by T4m** [lsuits/block_quickmail#264]
https://github.com/lsuits/block_quickmail/blob/cabf093e5ae1aae2188f733ca26f22181d4bd997/db/install.xml#L204

It seems that the following keys have been added without test:
```
        <KEY NAME="course_id" TYPE="foreign" FIELDS="course_id" REFTABLE="course" REFFIELDS="id"/>
        <KEY NAME="user_id" TYPE="foreign" FIELDS="user_id" REFTABLE="user" REFFIELDS="id"/>
        <KEY NAME="alternate_email_id" TYPE="foreign" FIELDS="alternate_email_id" REFTABLE="block_quickmail_alt_emails" REFFIELDS="id"/>
        <KEY NAME="signature_id" TYPE="foreign" FIELDS="signature_id" REFTABLE="block_quickmail_signatures" REFFIELDS="id"/>
```
It fails on plugin install. Do we need to add the missing fields ? Or restore the absence of these new references ?

**Comment by rrusso** [comment]
This has been resolved in master. This was a copy pasta back when Chad originally wrote it. All our testing was on upgrades. I feel embarrassed we missed this and it took so long to get to it.
