### ISSUE TITLE
Error when sending admin email

### ISSUE THREAD

**Issue by jtsafran** [lsuits/block_quickmail#266]
When trying to send an admin quickmail using the latest version on Moodle.org (2017122001) and Moodle 3.5, we see the error below.  It looks like the admin_email.php file is no longer part of the package on GitHub, though, possibly fixing this.  Will the github version be moving to Moodle.org, or shall we start pulling the code from Git?

Thanks for the excellent plugin!

-----------------------------------

Coding error detected, it must be fixed by a programmer: Invalid database query parameter value

More information about this error
Debug info: Objects are are not allowed: stdClass
Error code: codingerror
Stack trace:

    line 859 of /lib/dml/moodle_database.php: coding_exception thrown
    line 878 of /lib/dml/moodle_database.php: call to moodle_database->detect_objects()
    line 1149 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->fix_sql_params()
    line 1902 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_recordset_sql()
    line 331 of /lib/enrollib.php: call to moodle_database->record_exists_sql()
    line 6075 of /lib/moodlelib.php: call to enrol_get_shared_courses()
    line 5823 of /lib/moodlelib.php: call to can_send_from_real_email_address()
    line 93 of /blocks/quickmail/classes/message.php: call to email_to_user()
    line 150 of /blocks/quickmail/admin_email.php: call to Message->send()

**Comment by rrusso** [comment]
You should be using the master branch of the GitHub repo for Moodle 3.5 and up.
