### ISSUE TITLE
Teachers unable to view sent messages

### ISSUE THREAD

**Issue by heather-williams** [lsuits/block_quickmail#268]
Quickmail 
$plugin->version = 2018091200;

Moodle verison:
Moodle 3.5.3 (Build: 20181112)

Completed migration of data from v1 to v2 and teachers are unable to view sent messages. They go into the course and choose to view sent message history and then clicking the button to view the message just redirects them back to the dashboard (/my). No debugging is given to tell us why.

**Comment by rrusso** [comment]
It may be a permission issue as it checks they have the appropriate privileges and if they do not, redirect to /my.

Also I have an improvement coming that allows the instructor to download previously sent attachments from the sent message screen.

**Comment by heather-williams** [comment]
All quickmail permissions are set to allow for the Teacher role.

**Comment by rrusso** [comment]
What is the Quickmail FERPA mode set to and what is the course group mode set to?

**Comment by heather-williams** [comment]
course group mode is no groups FERPA mode is set to "respect course mode".

**Comment by rrusso** [comment]
Sorry

**Comment by heather-williams** [comment]
since that version is not on moodle.org, I'm guessing our dev team did pull it from github. We tried to pull the latest version but our dev team filed an issue here (https://github.com/lsuits/block_quickmail/issues/263) and is waiting for it to be fixed before pulling a newer version.

**Comment by rrusso** [comment]
I have backups completing now and am working on restoring the data in a useful manner. I will update master when done. This will ONLY backup messages and settings, not recipients as this is a VERY complex process due to the structural changes and recipient statuses and events and future messages - never mind the fact the restored course might not have the same users in it.

**Comment by rrusso** [comment]
Backup and Restore are now functional in the latest master and an upgrade will be triggered on install.

**Comment by rrusso** [comment]
Let me know if the latest master resolves your multiple issues. I tested a full backup and restore with all user data and the message logs were backed up and restored without the recipients.

**Comment by heather-williams** [comment]
The latest version does resolve the issue. However our developer found another bug, which is preventing them from adding it to our internal repo (https://github.com/lsuits/block_quickmail/issues/270) anyway you could take a look at that?

**Comment by heather-williams** [comment]
@rrusso Any update on whether or not you can take a look at that #270 issue?

**Comment by heather-williams** [comment]
@rrusso Just pinging you to see if there's any update? It looks like those keys in #270 got added accidentally(?) added in your October merge? they weren't in your xml in the previous version....

**Comment by rrusso** [comment]
I’ll look at it later today. I’ve been swamped with unrelated work.

**Comment by heather-williams** [comment]
Awesome! Let me know! I have multiple sites waiting on the latest fixes. :-)

**Comment by rrusso** [comment]
Master is updated and installs clean on 3.1 and above.

**Comment by heather-williams** [comment]
Nice! Thank you!

**Comment by rrusso** [comment]
Again, this should be resolved in master. Please let me know if any issues crop up.
