### ISSUE TITLE
How to use Scheduled Sending?

### ISSUE THREAD

**Issue by eorfanelli** [lsuits/block_quickmail#273]
Hello, first of all thanks for the amazing work you are doing.

I see that there is the "Scheduled Sending" feature, and I was wondering how to set that up.
I can't see it neither in the quickmail block options nor in the quickmail composition page.
Any help would be appreciated, thanks a lot!

**Comment by rrusso** [comment]
Scheduled sending requires Quickmail V2, which is available for testing from the code_test branch.
