### ISSUE TITLE
Cannot send email in moodle 3.7

### ISSUE THREAD

**Issue by fschuett** [lsuits/block_quickmail#276]
I do select a group of users to send email to. The users move from column users to column selected.
If I press "send" I get the error "no_usersgroups" and mail is not send.

**Comment by rrusso** [comment]
Quickmail 2 will be required for 3.7 and above. I am in the process of finishing it. It's available on the code_check branch. If you'd like to test it, please provide feedback.

**Comment by fschuett** [comment]
Ok, I did check it out and installed it. I'll get back to you.
Thank you.
