### ISSUE TITLE
Hardcoded date format

### ISSUE THREAD

**Issue by t-schroeder** [lsuits/block_quickmail#278]
This plugin uses a hardcoded format when outputting dates, e.g. in the sent messages list:

https://github.com/lsuits/block_quickmail/blob/409edbeb3bcb492a5de7e89f9b559bb053fde984/classes/persistents/concerns/enhanced_persistent.php#L97

It uses that date format regardless of the display language. It would be nice if you could take into account the user's display language when rendering dates. Moodle has a couple of predefined date/datetime/time formats to choose from:

https://github.com/moodle/moodle/blob/master/lang/en/langconfig.php

Every language usually defines these formats. So I would suggest using something like this instead:

```php
return userdate($datetime, get_string('strftimedatetime'));
```

**Comment by rrusso** [comment]
Done and committed in code_check. Soon merging to master.
