### ISSUE TITLE
Supported user data fields showing

### ISSUE THREAD

**Issue by yongra** [lsuits/block_quickmail#281]
Is this normal to see these what looks like tags? I also attached the screen shot as well.

Supported user data fields:
[:firstname:]
[:lastname:]
[:fullname:]
[:middlename:]
[:email:]
[:alternatename:]
[:coursefullname:]
[:courseshortname:]
[:courseidnumber:]
[:coursesummary:]
[:coursestartdate:]
[:courseenddate:]
[:courselink:]
[:courselastaccess:]
[:studentstartdate:]
[:studentenddate:]

![2019-07-23_9-16-35](https://user-images.githubusercontent.com/4802115/61715369-fb6d8080-ad2a-11e9-94fa-ca910ba97237.jpg)

**Comment by rrusso** [comment]
Yes. These fields allow you to mail-merge user information such as first or last name into emails to an entire course for a more personalized feel.

**Comment by yongra** [comment]
Great. Thank you.

Ra

**Comment by yongra** [comment]
Can I ask why version 2 is not in the moodle.org site? It only has the version 1.7.x.


Ra

**Comment by rrusso** [comment]
I'm working on it.

**Comment by yongra** [comment]
Thank you.

Ra
