### ISSUE TITLE
Error when sending admin email

### ISSUE THREAD

**Issue by markt71** [lsuits/block_quickmail#282]
When I tried to send an admin email I was receiving the coding error below running Quickmail version 1.7.6 on Moodle version 3.5.5. While researching this issue I found the closed issue `https://github.com/lsuits/block_quickmail/issues/266` with a suggestion to update to the current master branch to fix the problem. However, once I updated to the master branch dated 15 days ago I started receiving other errors listed below. I am not sure how to resolve these new errors, and was wondering if you could help. Thank you for your time and support.

Original error with Quickmail version 1.7.6:
----------------------------------------------
Coding error detected, it must be fixed by a programmer: Invalid database query parameter value

More information about this error

Debug info: Objects are are not allowed: stdClass
Error code: codingerror
Stack trace:
line 859 of /lib/dml/moodle_database.php: coding_exception thrown
line 878 of /lib/dml/moodle_database.php: call to moodle_database->detect_objects()
line 1178 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->fix_sql_params()
line 1902 of /lib/dml/moodle_database.php: call to mysqli_native_moodle_database->get_recordset_sql()
line 331 of /lib/enrollib.php: call to moodle_database->record_exists_sql()
line 6154 of /lib/moodlelib.php: call to enrol_get_shared_courses()
line 5902 of /lib/moodlelib.php: call to can_send_from_real_email_address()
line 93 of /blocks/quickmail/classes/message.php: call to email_to_user()
line 150 of /blocks/quickmail/admin_email.php: call to Message->send()

New error message with Quickmail Master Branch:
-------------------------------------------------------
Notice: Undefined property: block_quickmail_broadcast_recipient_filter::$supported_fields in /var/www/html/moodle/blocks/quickmail/classes/broadcast_recipient_filter.php on line 91

Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in /var/www/html/moodle/blocks/quickmail/classes/forms/broadcast_message_form.php on line 26

**Comment by rrusso** [comment]
Resolved. Sorry about this one.

**Comment by rrusso** [comment]
So I've tested it after like…4 commits and it seems fine.
